{% set name = "pybobyqa" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/numericalalgorithmsgroup/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 08c22f85e509949e2e1b8ead7bcfe41de46fe75a1d7ee305bbbe89f460f2ee13

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.11
    - scipy >=0.17
    - pandas >=0.17

test:
  imports:
    - pybobyqa

about:
  home: https://github.com/numericalalgorithmsgroup/pybobyqa
  summary: Derivative-Free Solver for Bound-Constrained Minimization
  description: |
    Py-BOBYQA is a flexible package for solving bound-constrained general 
    objective minimization, without requiring derivatives of the objective. At 
    its core, it is a Python implementation of the BOBYQA algorithm by Powell, 
    but Py-BOBYQA has extra features improving its performance on some problems
    (see the papers below for details). Py-BOBYQA is particularly useful when 
    evaluations of the objective function are expensive and/or noisy.
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  doc_url: https://numericalalgorithmsgroup.github.io/pybobyqa/

extra:
  recipe-maintainers:
    - vitenti
    - marcpaterno
