{% set name = "pybobyqa" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/numericalalgorithmsgroup/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 54ea42c07b5d47832d5f7c2b6e03126884b23761753e14eb30a3dacca2cfcf7f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.11
    - scipy >=0.17
    - pandas >=0.17

test:
  requires:
    - python {{ python_min }}
  imports:
    - pybobyqa

about:
  home: https://github.com/numericalalgorithmsgroup/pybobyqa
  summary: Derivative-Free Solver for Bound-Constrained Minimization
  description: |
    Py-BOBYQA is a flexible package for solving bound-constrained general 
    objective minimization, without requiring derivatives of the objective. At 
    its core, it is a Python implementation of the BOBYQA algorithm by Powell, 
    but Py-BOBYQA has extra features improving its performance on some problems
    (see the papers below for details). Py-BOBYQA is particularly useful when 
    evaluations of the objective function are expensive and/or noisy.
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  doc_url: https://numericalalgorithmsgroup.github.io/pybobyqa/

extra:
  recipe-maintainers:
    - vitenti
    - marcpaterno
